name: XNPlug
version: '${version}'

main: me.sl.XNPlug.XNPlug
api-version: '1.21.11'
load: POSTWORLD

commands:
  afk:
    description: 切换 AFK 状态
    usage: /afk
  list:
    description: 列出所有在线玩家
    usage: /list
